sudo: required

services:
    - docker

before_install:
    - travis_wait 50 docker build -t testfield .
    - docker build -t testfield_test -f DockerfileTests  .
    - docker ps -a

script:
    - docker run -it testfield_test test FUNCTEST lp:unifield-server lp:unifield-web


