#!/bin/bash

NETRPC_PORT=7006
WEB_PORT=7004
XMLRPC_PORT=7005
XMLRPCS_PORT=7007

UNIFIELDADMIN=admin
UNIFIELDPASSWORD=admin

DBPASSWORD=selenium_testing
DBADDR=127.0.0.1
DBUSERNAME=selenium_testing
DBPORT=7014
DBPREFIX='TESTS'

SERVER_HOST=127.0.0.1
SERVER_TMPDIR=/home/testing/repo
SERVER_ENVNAME=lightweight

DBPATH=/usr/lib/postgresql/9.6/bin/
FORCED_DATE=yes

HOMEREDB=$'ZXBpc2FnYQ==\naG9tZXJlN3pFcGljb25jZXB0MTIz'

