#!/usr/bin/env python

import utils

all_instances = [ "HQ1C1", "HQ1C1P2", "HQ2C1", "HQ1C1P1", "HQ1", "HQ2" ]

for i in all_instances:
	print "Doing initial container sync on", i
	utils.set_docker_hwid(i)
	utils.synchronize_instance(i)
