#!/bin/sh

set -e

if [ ! -d .git ]; then
	echo "Should be run from the top-level directory of testfield."
	exit 1
fi

git checkout -- .
git pull

if [ ! -L website/performances ]; then
	ln -s ../../precious-data/performances website
fi

if [ ! -L website/tests ]; then
	ln -s ../../precious-data/tests website
fi
